### ISSUE TITLE
Suggested companies

### ISSUE THREAD

**Issue by nancruz** [marmelo/tech-companies-in-portugal#1]
**OLX Group:** https://www.olxgroup.com/search/engineering/portugal-lisbon/all-brands

**Comment by nunoas** [comment]
**Pipedrive:**  CRM to make sales people more efficient
**Jobs:** https://www.pipedrive.com/jobs/portugal
**Link:** https://www.pipedrive.com
**Location:** Lisbon

**Comment by marmelo** [comment]
Hi @nancruz and @nunoas,

Can you please check [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) and contribute with pull requests?
Let me know if you have any trouble.

Thanks!

**Comment by nancruz** [comment]
@marmelo done 👍

**Comment by marmelo** [comment]
Thanks @nancruz!

**Comment by marmelo** [comment]
Hi @nunoas, do you need some help?  
I bet @claudiaalves is ready to come to the rescue! :)

**Comment by marmelo** [comment]
Hi @nunoas @claudiaalves, I am closing this issue.
Feel free to open a pull request for Pipedrive.
Thanks!
