### ISSUE TITLE
What about companies working in multiple different areas? 

### ISSUE THREAD

**Issue by ClaymorePT** [marmelo/tech-companies-in-portugal#117]
Like [VOID.pt](http://void.pt/)?

WEb development, Blockchain related development and Cyber security to name a few?

**Comment by gcandal** [comment]
Consultancy 👨‍💼 > Specialized 🎯?

**Comment by marmelo** [comment]
Hi @ClaymorePT,

If there are multiple areas I suggest selecting the one the company fits best.
I am updating the CONTRIBUTING.md file with this information.

Thanks!
