### ISSUE TITLE
Add companies without verification they work in Portugal?

### ISSUE THREAD

**Issue by vpereira01** [marmelo/tech-companies-in-portugal#128]
Should companies that have 0 references to work in Portugal be added?

It's my opinion that if the company site, or job vacancies, have no mention of working in Portugal they should no be added.

#127 Was the second time I noticed this. The company site has 0 references to Lisbon. The same goes for the job offers site that actually has 0 vacancies.

It's fine to trust people and all, but it's weird to check a company in the list that has no mention to work in Portugal.

**Comment by marmelo** [comment]
Hi @vpereira01,

You are right, I often trust too much.
I will try to pay more attention next time.

Thanks for calling this out.

**Comment by marmelo** [comment]
Hi @wiiaboo,

Can you please inform us if there are tech people working at Fruition Partners' offices in Fundão and/or Lisbon?

Thanks.

**Comment by wiiaboo** [comment]
Yeah, both Fundão and Lisbon have developer offices with about 30 consultants/app developers (I'm one of them) and 15(?) in SecondHome, respectively. The PT offices are a branch of the Netherlands/NCE part of Fruition.

**Comment by vpereira01** [comment]
Issue raised and cleared.
