### ISSUE TITLE
Split companies into categories.

### ISSUE THREAD

**Issue by marmelo** [marmelo/tech-companies-in-portugal#13]
As the number of companies grow we must think about creating some categories.
Some are becoming evident but others only contain one or two companies.

The following table will be used to organize the categories until they are created.
Please help me assign the companies to the right categories!

| Category | Companies |
| - | - |
| 🚗 Automotive | Critical TechWorks, Mercedes-Benz.io, Stratio Automotive |
| 🛠 Developer Tools | Codacy, DashDash, Onfido, OutSystems, Probely, Unbabel |
| 🚒 Consultancy | AddCode, Armis, Critical Software, Imaginary Cloud, KI labs,<br> Kwanko, Mindera, Moxy, Premium Minds, Pixelmatters,<br> Redlight Software, Subvisual, Thing Pink, YLD |
| 🏢 Enterprise Software<br>(ERP, MES, CMS, ...) | Critical Manufacturing, Primavera BSS, Unit4, Sherpany,<br>WeDo Technologies |
| 👠 E-commerce | Blip, Farfetch, Hostelworld, OLX, Platforme, Trouva, Zalando |
| 💰 FinTech | Feedzai |
| 🎥 Multimedia | MOG Technologies, Sky | 
| :couple: Social | YouClap |
| 📞 Telcos | Altice Labs, GoContact, Talkdesk, WIT Software |

**Comment by marmelo** [comment]
Hi @rgomesf @rjcarneiro @tmendo @JoaoMatos @nancruz @afonsojramos @guilhermevpinto @gcandal.

Do you agree with the above categorisation? Feel free to suggest moves or category additions.
I want to wait for some more companies to be added to the list before refactoring, but I want to keep companies groomed and ready to go.

Thanks!

**Comment by guilhermevpinto** [comment]
Sure. Everything seems OK. 👍 
It sounds a little bit odd to see Blip on a Gaming category, though. Bookmaking would be more accurate but it would end up being too restrictive, I guess... and that's my only suggestion.

Good job. 😉

**Comment by JoaoMatos** [comment]
Looks good to me. I'm sure new categories will pop up as new companies are added.

Awesome job on the categorization and repo. 👌🏻

**Comment by rjcarneiro** [comment]
Well, critical manufacturing is like an ERP for manufacturers. Doesn’t fit in consultancy if you ask me....

**Comment by rjcarneiro** [comment]
I would create “Enterprise Software” category and add all companies that develops ERP, MES, CM/S, etc.

**Comment by marmelo** [comment]
Thanks @guilhermevpinto, renamed Blip's category for now.  
Lets wait if others similar join the list.

Thanks @rjcarneiro, created the category you suggested.
Lets wait if others similar join the list.

Thanks @JoaoMatos!

**Comment by afonsojramos** [comment]
Looks good to me, because even though some categories are kind of restrictive, I think they need to be!

**Comment by rjcarneiro** [comment]
Looks great!

**Comment by gcandal** [comment]
LGTM. Would maybe consider merging _Trading_ and _Fashion_ under a more general _E-Commerce_ category, but don't really have a strong opinion about it.

**Comment by nancruz** [comment]
Looks good.

Does it make sense to add the selling process category, e.g., if it is B2B or B2C?
