### ISSUE TITLE
http://www.vwds.pt/ is down

### ISSUE THREAD

**Issue by joaoportela** [marmelo/tech-companies-in-portugal#130]
Volkswagen digital solutions website is down and seems to be like that for quite some time.

- Does the company still exist?
- Should I submit a PR removing it?
- Update the website instead? To what? Their linkedIn?

**Comment by vpereira01** [comment]
Usually the PR (like yours #129 ) is not blocked with build issues that existed before but it's good not to like build issues :)

I think your #131 pr to fix this issue is a good idea.

**Comment by vpereira01** [comment]
@afonsojramos Do you know if that site is supposed to be dead?

**Comment by ftonato** [comment]
Hey @joaoportela,

Do you know whether this company is or not using _Nodejs_?

> https://github.com/ftonato/nodejs-in-portugal

**Comment by joaoportela** [comment]
No ideia. I was just trying to fix their broken link. 😅

**Comment by teamlyzer** [comment]
@joaoportela  It's the IT department of http://www.volkswagen-groupservices.pt

**Comment by vpereira01** [comment]
Their site is back up so I think this issue is done.

**Comment by marmelo** [comment]
Hi @joaoportela,

Thanks for taking the initiative to fix the website.
But like @vpereira01 stated, it seems that the existing vwds.pt is back online.

I am closing this issue and your pull request.

Thanks again!
