### ISSUE TITLE
Broke build 141034592

### ISSUE THREAD

**Issue by vpereira01** [marmelo/tech-companies-in-portugal#151]
Creating an issue so that PRs can reference this and it's easier to manage (I think).

https://travis-ci.com/marmelo/tech-companies-in-portugal/builds/141034592

* Glintt site is broken again (ref #105 ) with a HTTP 401 - Added on #93
* Foreteller site is a gone - Added on #111
* Javali regular failed connection

For Glintt I would add it to the white list since this a recurring issue.

For Foreteller it seems that they let their web hosting expire. Not sure if the company is gone since their social media activity seems to have stopped in September but Linkedin still shows people working there. I would ignore that error for but not whitelist it.

Is it possible to make the bot retry failed connections? It seems a recurring issue that could be avoided with a retry of the connection.

**Comment by marmelo** [comment]
Hi @vpereira01,

I agree with with you suggestions.

@afonsojramos do you know if Foreteller is still alive?

We are using [dkhamsing/awesome_bot](https://github.com/dkhamsing/awesome_bot) to check the links.
AFAIK there is no retry option.

Thanks!

**Comment by vpereira01** [comment]
What do you think about using [Danger](https://github.com/dkhamsing/awesome_bot#danger) on the repo?

I was trying to use GitHub Actions instead of Travis+Danger to achieve the same result but awesome_bot doesn't work. I think awesome_bot depends on being executed on a TTY which github action doesn't have.

I also tried to use some node.js tools because it could use a retry but their logging of the error isn't great (they only say it's a dead link).
