### ISSUE TITLE
Add loggi

### ISSUE THREAD

**Issue by pedrorijo91** [marmelo/tech-companies-in-portugal#168]
as per:

* https://insider.dn.pt/noticias/unicornio-brasileiro-das-entregas-abre-escritorio-em-portugal-tem-100-vagas/23355/
* https://jobs.kenoby.com/loggi/job/senior-software-engineer-lisbon/5e2b3f1c7bf6663c5f507b98

not sure about the best category tbh (seems to be similar to Glovo)

**Comment by vpereira01** [comment]
I think the best way is to make a Pull Request for it instead of asking for it to be added. A couple of Pull Requests like that are already open so you can see them as an example.
