### ISSUE TITLE
add Damia Group

### ISSUE THREAD

**Issue by sofiaunicorn** [marmelo/tech-companies-in-portugal#176]
Hi! It is possible add Damia Group Portugal (www.damiagroup.pt) at Consultancy Recruiting.
Lisbon  + Remote
Thank you.

**Comment by vpereira01** [comment]
This repository, like others in GitHub, is expanded by other making contributions with Pull Requests. If you're not familiar with this terms/workflows/etc. I think it's better to ask someone on the team/company to do it or help you with it.

**Comment by marmelo** [comment]
Hi @sofiaunicorn, @AntWecki has submitted a pull request and Damia is already in the list.
