### ISSUE TITLE
[Discussion] Maintainer help

### ISSUE THREAD

**Issue by afonsojramos** [marmelo/tech-companies-in-portugal#208]
In the past months this repository has seen stuck issues and PRs for days or months. @marmelo do you need help maintaining this project? I think it has a great impact in our "tech-scene", and it is important that it is updated.

@vpereira01 what do you think, since you are also an active contributor to this repository.

**Comment by mmar** [comment]
I only came across this recently, but I also found it to be particularly relevant and I’m available to help out if needed.

**Comment by waldyrious** [comment]
In wiki-like repositories like this, I have seen a successful model of collaboration where people who submit one (or N) PRs that get merged, are automatically given commit rights in the repo. This model, coupled with a branch protection rule (see below) requiring, say, 2 or 3 approvals for a PR to be merged, is often sufficient to ensure the community is self-sufficient and replenishes naturally as existing maintainers' availability gets reduced (which invariably happens sooner or later).

![Screenshot 2021-02-03 at 15 52 25](https://user-images.githubusercontent.com/478237/106772407-e370ff80-6637-11eb-82e7-8df4258e252c.png)

We've been using a [similar process](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) at tldr-pages for a while now, and it's been working great!

**Comment by vpereira01** [comment]
I'm able and willing to help :)

The tldr-pages model seems nice but also too complex for this since it requires an organisation.

In order to simplify my suggestion is for @marmelo to add 3 collaborators that review and merge pull requests and enable master branch protection to require 2 approving reviews. This way PRs can flow better and @marmelo can be off more time.

**Comment by afonsojramos** [comment]
@waldyrious I'll have to agree with @vpereira01 here, I think our scope is much smaller than [tldr-pages](https://github.com/tldr-pages/tldr#readme). Furthermore, I think that there are already more than 3 collaborators that have the objectives well aligned for this repository. In the future, we can always expand the said list of contributors if required. 

Obviously, I'm also willing and able to help :)

**Comment by marmelo** [comment]
I agree it is time to open access to others.
I have just added @vpereira01, @afonsojramos and @pedrorijo91 as contributters.

You are the top 3:
https://github.com/marmelo/tech-companies-in-portugal/graphs/contributors

I have enforced the following policy:
![2021-02-03-175718_1396x1642_scrot](https://user-images.githubusercontent.com/247440/106788874-74040b80-6649-11eb-8060-137dba35897e.png)

Let me know what you think.

**Comment by afonsojramos** [comment]
Thank you @marmelo! Those policies seem fitting.

I'll wait for the 👍 from @vpereira01 and @pedrorijo91 on your comment before closing the issue.

**Comment by vpereira01** [comment]
Sounds good to me :)

**Comment by pedrorijo91** [comment]
LGTM

**Comment by afonsojramos** [comment]
@marmelo would you reconsider reducing the number of approvals to 2? It is getting a bit clogged if a PR is created by one of us.
