### ISSUE TITLE
New Tech Company - automotive category

### ISSUE THREAD

**Issue by filipepiedade** [marmelo/tech-companies-in-portugal#214]
[cloudmobility](https://cloudmobility.io/) [🚀](https://cloudmobility.io/career) | Special purpose cloud for mobility and transportation. | Lisboa

**Comment by filipepiedade** [comment]
Did I done something wrong? What can I do to add cloudmobility to the list of tech companies?

**Comment by filipepiedade** [comment]
Did I done something wrong? What can I do to add cloudmobility to the list of tech companies?

**Comment by afonsojramos** [comment]
@filipepiedade it is already on the list, don't worry, I've added it in PR #215
