### ISSUE TITLE
Thing Pink seems to have ended

### ISSUE THREAD

**Issue by vpereira01** [marmelo/tech-companies-in-portugal#217]
@lauraalpinto Do you know if Thing Pink thing-pink.pt still exists and/or still has tech jobs?

From my perspective the company has ended, the site is dead and the social media presence seems to also have stopped a year ago.

You added the company on the PR #18

**Comment by afonsojramos** [comment]
@Xplouder can you help here?

**Comment by teamlyzer** [comment]
Thing Pink is now the 7EGEND 

https://www.insidesport.co/ronaldo-to-launch-his-own-tech-brand-7egend-0301082017/

**Comment by Xplouder** [comment]
@afonsojramos I can confirm that the Thing Pink changed the name to 7egend ~2 years ago.
