### ISSUE TITLE
Split companies into regions

### ISSUE THREAD

**Issue by filfreire** [marmelo/tech-companies-in-portugal#26]
👋  @marmelo 
Suggestion: split the list per regions/cities like: Porto, Lisboa, ...

**Comment by marmelo** [comment]
Hi @filfreire,

I understand this would be great but how would you manage companies with multiple offices?

Thanks.

**Comment by filfreire** [comment]
@marmelo I'd suggest a duplicate entry for companies in that case.

**Comment by marmelo** [comment]
Hi @vpereira01,

Right now I don't believe we should duplicate companies to accommodate regions.
If anyone want to search companies in any city they can use the browser's Find feature.

I am closing this issue.
Thanks!
