### ISSUE TITLE
Remove/Update Natixis?

### ISSUE THREAD

**Issue by vpereira01** [marmelo/tech-companies-in-portugal#299]
There has been a rebrand of the company the now the site just redirects to this https://natixis.groupebpce.com/natixis/en/home-j_6.html

**Comment by afonsojramos** [comment]
Intersting 🤔 @marianasilva14 can you give some insight here, please? 😄

**Comment by marianasilva14** [comment]
Hello Afonso,

Sim, agora a Natixis faz 100% parte do grupo BPCE e por isso até o site
devem ter alterado 😀

Espero que estejas bem!!
Um beijinho

Afonso Jorge Ramos ***@***.***> escreveu em ter., 13/09/2022
às 22:40 :

**Comment by afonsojramos** [comment]
Thanks Mariana! I guess that's settled then!
