### ISSUE TITLE
Rules should state if referral links are allowed

### ISSUE THREAD

**Issue by nantunes** [marmelo/tech-companies-in-portugal#33]
Companies might have Referral Rewards for its employees if a candidate is hired using an unique link.

I have no opinion if we should allow it or not, but the rules should clear it out, one way or another.

**Comment by marmelo** [comment]
I do not want to monetise this repository.  
So I would tend to say no to referral links.
Lets wait and see what others think.

Thanks for bringing this up @nantunes!

**Comment by marmelo** [comment]
I have just updated [CONTRIBUTING.md](https://github.com/marmelo/tech-companies-in-portugal/blob/master/CONTRIBUTING.md) with this information.
Thanks.
