### ISSUE TITLE
Kitch may have ceased

### ISSUE THREAD

**Issue by vpereira01** [marmelo/tech-companies-in-portugal#343]
- Corporate site HTTP 404 since May 28th https://github.com/marmelo/tech-companies-in-portugal/actions/runs/5102775556
- Careers site also gives Not Found https://apply.workable.com/kitch/
- Previously acquired by Glovo https://www.crunchbase.com/acquisition/glovo-app-acquires-kitch--e6e17fc6
- Linkedin Page stop posting for 5 months https://www.linkedin.com/company/kitch-io/
- Rumored to ceasing operations https://pt.teamlyzer.com/news/kitch
- Added on #259

I think it make sense to wait another week.

@afonsojramos  do you have any insight on this company?

**Comment by pedrorijo91** [comment]
many people from Kitch seem to have left for other companies. so it's likely it may be closing operations, or at least downsizing.

**Comment by afonsojramos** [comment]
@vpereira01 funny you asked 😅 I believe it was acquired by Glovo if I'm not mistaken. I'm out atm so I have no way of checking, but I'm 90% sure of this.
