### ISSUE TITLE
[Suggestion] Techstacks

### ISSUE THREAD

**Issue by pmiguel** [marmelo/tech-companies-in-portugal#44]
### Suggestion
Just leaving a little suggestion, or at least open the discussion about it.

Somehow displaying each company's tech stacks. I believe this would be a useful feature, but I'm afraid it might cluster the simplicity of the list.

### Stackshare
Recently I've come across with [Stackshare](https://stackshare.io/), which might be a way of linking each company's tech stack, without cluttering the interface too much. Adding a symbol such as 💻,🔧 or 🏢 might be a way of representing the link with iconography, not unlike 🚀 already in use.

**Comment by vpereira01** [comment]
Solved by #209
