### ISSUE TITLE
Use email instead of link for career/recruitment

### ISSUE THREAD

**Issue by rjmAmaro** [marmelo/tech-companies-in-portugal#56]
Is it possible to use something like a 'mailto' instead of the link for the careers/recruitment?

**Comment by gcandal** [comment]
Why? What are the pros & cons of the change?

**Comment by rjmAmaro** [comment]
We don't have a webpage for recruitment :sweat_smile:

**Comment by neteinstein** [comment]
Maybe time to create one? :-P

**Comment by vpereira01** [comment]
@rjmAmaro Are you asking for all the careers URLs to be mailto:a@b.pt or questioning if it's possible to add an entry with a mailto:a@b.pt for careers URL?

The title of this issues indicates that you are asking for an overall change.

**Comment by marmelo** [comment]
Hi @rjmAmaro, I don't believe we should have mailto links.  

The main objective of a Careers link is for people to easily discover existing opportunities.
If they want to contact a company I am sure they can find out its email inside the company website.

That said, I have just updated [CONTRIBUTING.md](https://github.com/marmelo/tech-companies-in-portugal/blob/master/CONTRIBUTING.md) with this information.

I am closing the issue, thanks!
