### ISSUE TITLE
Create Security section.

### ISSUE THREAD

**Issue by marmelo** [marmelo/tech-companies-in-portugal#74]
Hi, what do you think about creating a **Security** 🔒 section with the following companies?

- Dashlane @StanKocken 
- JScrambler @pmiguel 
- Onfido @dnlserrano 
- Probely @tmendo 
- Symantec @symc-bernardo-patrao 

I can do it, just wanted to know if you are OK with that.

Thanks.

**Comment by pmiguel** [comment]
Completely okay, go ahead 😁

**Comment by marmelo** [comment]
It will look like the following, just waiting some time for people to comment.

## Security :lock:

  | Company | Description | Locations |
 | :------ | :---------- | :-------- |
 | [Dashlane](https://www.dashlane.com/) [:rocket:](https://www.dashlane.com/about/careers) | Password manager and online security app. | `Lisboa` |
 | [JScrambler](https://jscrambler.com) [:rocket:](https://jscrambler.com/careers) | JavaScript application integrity and security. | `Porto` |
 | [Onfido](https://www.onfido.com) [:rocket:](https://onfido.com/jobs/) | Identity verification at the speed of life. | `Lisboa` |
 | [Probely](https://probely.com) [:rocket:](https://careers.probely.com) | Automated web application security scanning as a service. | `Lisboa` |
 | [Symantec](https://www.symantec.com) [:rocket:](https://www.symantec.com/about/careers) | Enterprise and Consumer Security Products. | `Coimbra` `Remote` |

**Comment by StanKocken** [comment]
That sounds perfect! Thanks for doing that.

**Comment by dnlserrano** [comment]
I'm not sure, TBH, we also fit in the FinTech space, but looks alright. 👍

**Comment by marmelo** [comment]
@dnlserrano in which category do you believe Onfido fits best?
Developer Tools (the current one), Security (the one proposed), Fintech or other?

Thanks!

**Comment by dnlserrano** [comment]
FinTech, please. Thanks!

**Comment by vpereira01** [comment]
Two more entries 

- https://www.integrity.pt/
- https://www.binaryedge.io/ - I head they had people in Lisbon but checking the site I'm not sure

**Comment by vpereira01** [comment]
Another one, https://www.visionware.pt

I think that's enough for a category and I bet there's a little more companies more security focused.

**Comment by teamlyzer** [comment]
Another well known company

- https://www.layer8.pt/
