### ISSUE TITLE
Armis links are broken.

### ISSUE THREAD

**Issue by marmelo** [marmelo/tech-companies-in-portugal#81]
Hi @rjcarneiro, both Armis links seem to be broken (which makes the build fail):

http://www.armisgroup.com/
http://www.armisgroup.com/ofertas-de-trabalho/

Do you know what is happening?
Thanks.

**Comment by rjcarneiro** [comment]
I have no clue but if I had to guess, they are releasing a new website?

**Comment by rjcarneiro** [comment]
Yep, I was right... websites back online @marmelo

**Comment by marmelo** [comment]
Thanks @rjcarneiro!
