### ISSUE TITLE
Split Consultancy category into sub-categories.

### ISSUE THREAD

**Issue by marmelo** [marmelo/tech-companies-in-portugal#82]
The **Consultancy** :man_office_worker: is growing a lot and I feel that some sub-groups are forming.

I do not know all companies and need you help to both find out the emerging categories and also to assign companies to the best category they fit.

Right now, I am proposing the following sub-categories.
New sub-categories are expected to popup as time goes by.

- Consultancy :man_office_worker: Broad :dizzy: 
- Consultancy :man_office_worker: Specialized :dart: 
- Consultancy :man_office_worker: Web :globe_with_meridians: Mobile :iphone: Design :art: 
- Consultancy :man_office_worker: Recruiting :male_detective:

What do you think?
(people that contributed with these companies, hope I don't miss someone)
@pmoalmeida @rjcarneiro @goblindegook @rjmAmaro @fsschmitt @afonsojramos @froque @vpereira01 @rmachado-ubiwhere @carlosfaria94 @CaboML @pedrosousa13 @glynrob @rgllm @andrepcg @lauraalpinto @Couto @antoniomapinho @leplastic @filipeoliveiraa @RicCastelhano @pdfrod

## Consultancy :man_office_worker: Broad :dizzy:

| Company | Description | Locations |
| :------ | :---------- | :-------- |
| [AddCode](https://addcode-io.breezy.hr) [:rocket:](https://addcode-io.breezy.hr/#positions) | Software engineering. | `Porto` |
| [Armis](http://www.armisgroup.com/) [:rocket:](http://www.armisgroup.com/ofertas-de-trabalho/) | Technology development and consultancy. | `Lisboa` `Porto` |
| [Equal Experts](https://www.equalexperts.com) [:rocket:](https://www.equalexperts.com/contact-us/lisbon/) | Making software. Better. | `Lisboa` `Remote` |
| [LIS @ IPN](https://www.ipn.pt/laboratorio/LIS) | Technological R&D and innovative multi-disciplinary projects. | `Coimbra` |
| [KI labs](https://ki-labs.com/) [:rocket:](https://ki-labs.com/careers/) | Solve complex tech and business challenges for big corporations. | `Lisboa` |
| [Mindera](https://mindera.com) [:rocket:](https://mindera.com/#we-are-hiring) | Technology development and consultancy. | `Aveiro` `Porto` |
| [Moxy](https://moxy.studio) [:rocket:](https://moxy.studio/team#join-the-team) | Interdisciplinary studio focused on design and development. | `Porto` |
| [Premium Minds](https://www.premium-minds.com/) [:rocket:](https://join.premium-minds.com/) | We build great software for innovative clients. | `Lisboa` |
| [TMC](https://tmc-employeneurship.com/) [:rocket:](https://www.linkedin.com/company/tmcspain/jobs/) | Agile software development. | `Porto` |
| [Ubiwhere](https://ubiwhere.com) [:rocket:](https://www.ubiwhere.com/en/careers) | Bleeding Edge Technologies with custom R&D. | `Aveiro` `Coimbra` |

## Consultancy :man_office_worker: Specialized :dart: 

| Company | Description | Locations |
| :------ | :---------- | :-------- |
| [Critical Software](https://www.criticalsoftware.com) [:rocket:](https://www.criticalsoftware.com/careers) | Mission and business-critical applications. | `Coimbra` `Lisboa`<br>`Porto` |
| [blockbird Ventures](https://www.blockbird.ventures) [:rocket:](https://blockbird.ventures/careers/) | Blockchain and Ethereum development. | `Lisboa` `Remote` |
| [JTA](https://www.thedatascientists.com/) [:rocket:](https://www.thedatascientists.com) | Machine Learning, Reporting and custom vizualizations services. | `Porto` |
| [Kwanko](https://kwanko.com/) [:rocket:](https://www.kwanko.com/en/careers-join-kwanko-group-check-out-our-job-offers/#offres) | An International leader in Crossdevice Performance Marketing. | `Lisboa` |

## Consultancy :man_office_worker: Web :globe_with_meridians: Mobile :iphone: Design :art:

| Company | Description | Locations |
| :------ | :---------- | :-------- |
| [Dengun](https://www.dengun.com/en/) [:rocket:](https://www.dengun.com/en/jobs/) | Web, Mobile development and digital marketing. | `Faro` |
| [Imaginary Cloud](https://www.imaginarycloud.com) [:rocket:](https://www.imaginarycloud.com/careers) | Web, mobile, development and design services. | `Lisboa` |
| [Pixelmatters](http://pixelmatters.com) [:rocket:](http://pixelmatters.com/jobs/) | Digital product design and development company. | `Porto` |
| [Redlight Software](https://weareredlight.com) | Web and mobile development studio focused on products. | `Coimbra` `Lisboa` |
| [Subvisual](https://subvisual.co/) [:rocket:](https://subvisual.co/company/join-us/) | Web development and design firm. | `Braga` |
| [Thing Pink](http://www.thing-pink.pt) [:rocket:](http://www.thing-pink.pt/joinus) | Digital Agency with focus on Web, Mobile and IoT. | `Lisboa` `Porto` |
| [YLD](https://www.yld.io/) [:rocket:](https://www.yld.io/join-us/) | Software engineering, design, training and open-source. | `Lisboa` `Porto`<br>`Remote` |

## Consultancy :man_office_worker: Recruiting :male_detective: 
Outsourcing and Permanent Placement.

| Company | Description | Locations |
| :------ | :---------- | :-------- |
| [Affinity](https://affinity.pt) [:rocket:](https://affinity.pt/en/careers/) | Consultancy, Outsourcing. | `Lisboa` `Porto` |
| [AGAP2](http://www.agap2-it.pt/Agap2IT) [:rocket:](http://www.agap2-it.pt/Agap2IT/pt/pages/carreira/) | Consultancy, Outsourcing. | `Lisboa` `Porto` |
| [Alter Solutions](https://www.alter-solutions.com/pt-pt/) | Consultancy, outsourcing and nearshore projects. | `Lisboa` `Porto` |
| [BOLD International](https://www.boldint.pt/) [:rocket:](https://www.boldint.pt/carreiras/) | Consultancy, Outsourcing. | `Lisboa` `Porto` |
| [Everis](https://www.everis.com/portugal/pt-pt/home-pt) | Consultancy, Outsourcing. | `Lisboa` |
| [GLanDrive](https://www.glandrive.pt) | Consultancy, Outsourcing. | `Lisboa` `Porto` |
| [KWAN](https://www.kwan.pt/) | Tech Talent Done Right. | `Lisboa` `Porto` |
| [Prime IT](https://www.primeit.pt/) [:rocket:](https://www.primeit.pt/carreiras) | Consultancy, Outsourcing. | `Lisboa` `Porto` |

**Comment by vpereira01** [comment]
According to the companies descriptions seems to fit. Since this will impact all PRs I would advise for quick merge and fix later.

In more broad discussions I think Consultancy sub categories aren't that great but it's always hard to split them. Not sure what are the characteristics that matter in a consultancy company... Size (head count) ? Yes/No outsourcing? Specialized or broad projects? 

I would care more about size and if they specialize on something. That would be like Consultancy 👨‍💼👩‍💼  Specialized 🎯 (two persons, mid-sized)

**Comment by rjcarneiro** [comment]
I believe Armis belongs to Consultancy 👨‍💼 Specialized 🎯 because their area are:
-  Logistics and Transports
- Digital Sports

**Comment by afonsojramos** [comment]
The consultancy is truly too big at the moment, so I fully agree with this splitting. 

Regarding the categories themselves, I think for now they are okay, but may have to tuned afterwards!

**Comment by marmelo** [comment]
I have just split Consultancy companies into sub-categories.  
Feel free to suggest further moves and new sub-categories.  
Thanks!
